DECLARE @CONSULTA NVARCHAR(MAX)

DECLARE CURSOR_DESATIVA_TRIGGER CURSOR FOR

SELECT 'DISABLE TRIGGER '+g.name+' ON '+t.name+';' AS RESULT
  FROM sys.objects g join sys.objects t on g.parent_object_id=t.object_id
 WHERE g.type_desc='SQL_TRIGGER'
   AND t.type_desc='USER_TABLE'

OPEN CURSOR_DESATIVA_TRIGGER

FETCH NEXT FROM CURSOR_DESATIVA_TRIGGER INTO @CONSULTA

WHILE @@FETCH_STATUS = 0
BEGIN

EXEC(@CONSULTA)

    FETCH NEXT FROM CURSOR_DESATIVA_TRIGGER INTO @CONSULTA
END

CLOSE CURSOR_DESATIVA_TRIGGER
DEALLOCATE CURSOR_DESATIVA_TRIGGER